spring.application.name=job-board
spring.datasource.url=jdbc:postgresql://localhost:5433/job_board_db
spring.datasource.username=postgres
spring.datasource.password=200704

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=miki_super_secret_key_job_board_2024_secure
jwt.expiration=86400000

file.upload-dir=uploads